version: "3"

services:
  api:
    command: "poetry run python manage.py runserver 0.0.0.0:8000"
    tty: true
    build: ./api/.
    volumes:
      - ./api/.:/usr/src/app
    ports:
      - "8000:8000"
